### PR TITLE
🦄 Bump API to support ocp 4.x 🔥

### PR DESCRIPTION
**Pull request by springdo**
#### What is this PR About?
🦄 Bump API to support ocp 4.x 🔥

#### How do we test this?
`oc process | oc apply -f-` everything in this repo on a 4.x ocp cluster

cc: @redhat-cop/day-in-the-life

### CODE REVIEW

**Comment by springdo** [comment]
@garethahealy  - you wanna pick this up seeing as you're the king of api versions

**Comment by garethahealy** [comment]
Few you've missed:

Routes:
- jenkins/jenkins-ephemeral-template.yml
- jenkins/jenkins-persistent-template.yml
- pact-broker/pact-broker-deploy.yml

Template:
- jobs/slack-notify-job-template.yml

StatefulSets:
- prometheus/prometheus-template.yml
- scc/project-run-anyuid-template.yml

SecurityContextConstraints
- scc/project-run-anyuid-template.yml

**Review by tylerauerbeck — DISMISSED** [review]
LGTM (as is, just need to catch what @garethahealy mentioned above)

**Comment by springdo** [comment]
@garethahealy  - this is good to go!

**Review by garethahealy — APPROVED** [review]

**Pull request merged**
