### PR TITLE
cluster-crednetial-secret.yml - init commit

### PR DESCRIPTION
**Pull request by itewk**
This is for use with https://github.com/redhat-cop/pipeline-library/blob/master/vars/clusterCredentials.groovy

### CODE REVIEW

**Comment by oybed** [comment]
@itewk typo in filename. Otherwise, this looks very similar to the existing template:
https://github.com/redhat-cop/openshift-templates/blob/master/secrets/secret-generic-opaque.yml
Do you still want to keep both ? ... and if so, would it make sense to maybe name these files to better describe the differences? (keeping in mind that renaming the old one may cause issues for already existing usage).

**Comment by itewk** [comment]
@oybed fixed typo in file name.

Since https://github.com/redhat-cop/openshift-templates/blob/master/secrets/secret-generic-opaque.yml only works for storing one value and there is no way to do a variable number of values in a template (that I know of) I think its good to have this separate template. Where as the existing one is for generic use, this one has a specific purpose of storing the API end point and auth token for an OCP cluster. I guess another route to go would be to make a `secret-generic-opaque2.yml` that has two variable keys and values. I don't really love any of the solutions, but all the sample pipelines I have my clients using use this particular template for storing the login info for remote OCP clusters so thought it good to just have it up here rather then copy pasting it around.

**Comment by oybed** [comment]
Cool - thx for the info and details around alternatives. 

FYI: with the next openshift-applier release (v2.1.0), it will support .j2 templates and some of these things can be solved that way. However, that only works of course as long as the template(s) is used with a tool like the openshift-applier that lets you do that kind of pre-processing before applying it.

**Review by oybed — APPROVED** [review]
LGTM

**Pull request merged**
