### PR TITLE
Add docker-cfg secret template

### PR DESCRIPTION
**Pull request by tylerauerbeck**
Add a template to create a dockercfg secret

### CODE REVIEW

**Comment by pabrahamsson** [comment]
Possibly a concern, this will write the cleartext credentials in  `.metadata.annotations.kubectl.kubernetes.io/last-applied-configuration`.

**Comment by tylerauerbeck** [comment]
Agreed. The other option would be reverting back to just data and having the user know the format that everything needs to be in and providing the base64 encoded string containing all of the information.

**Comment by pabrahamsson** [comment]
I suppose it is ultimately the consumer of this template that has to decide if this is acceptable or not. Do we have a way to document this within this repository (or at least do it in the template itself)?
Any comments/thoughts from @redhat-cop/day-in-the-life ?

**Comment by etsauer** [comment]
@tylerauerbeck @pabrahamsson I would use data here and leave it to the user to encode the payload.

**Comment by tylerauerbeck** [comment]
I'm fine with that. I'll add a README in here to describe the steps that need to be done here. I've seen enough issues caused by issues in either the docker cfg layout or just forgetting to encode it that I think it's worth noting here.

**Comment by oybed** [comment]
@tylerauerbeck any updates on the README? Once that's done, we can merge.

**Comment by itewk** [comment]
@etsauer @tylerauerbeck my solution to the clear text password issue on https://github.com/redhat-cop/openshift-templates/pull/36/files was to pass the auth string rather then the username and password. Which since this is a secret and woudl only be base64 encoded anyways, i think strikes a good balance, i think we could even make the template take both so users could pass either. the reason I did the auth approach was that I didn't know you could pass username and pass separately like this. to create the auth you do:

`echo "USERNAME:PASSWORD" | base64`

**Comment by itewk** [comment]
@tylerauerbeck any luck on a new PR here? I am working on a PR for the https://github.com/redhat-cop/container-pipelines that is dependent on what the solution here is.

**Comment by itewk** [comment]
@tylerauerbeck @etsauer what are your thoughts on my suggestion to keep it stringData but pass the base64 `user:pass` that way the user doesn't have the complication of having to make the entire file contents themselves but the password isn't in clear text? seems to split the difference between the two concerns?

**Comment by tylerauerbeck** [comment]
@etsauer @pabrahamsson @oybed Made the changes discussed above. Changed to data and added instructions on the format/how to encode everything.

**Comment by tylerauerbeck** [comment]
@itewk Made the necessary changes here that were mentioned above. Just saw your comments. I don't think I have a preference either way.

**Review by oybed — APPROVED** [review]
LGTM - merging

**Comment by oybed** [comment]
@itewk this  PR has been open for quite some time, so decided to merge as-is with the current approach. I'm fine with your suggestion, however, so probably worth a follow-up PR as either a change to this existing file or maybe a separate file to provide the flexibility to do either.

**Comment by oybed** [comment]
@itewk BTW: just realized that PR https://github.com/redhat-cop/openshift-templates/pull/36 does exactly that, so probably worth just taking a look at that PR and merge it if everything looks good

**Comment by itewk** [comment]
@oybed yeah, I built #36 before I knew about this one being outstanding. Ill update #36 to have some sort of similar naming to this PR or find some creative way to combine or something.

**Pull request merged**
