### PR TITLE
Templates for InstallPlan Approver

### PR DESCRIPTION
**Pull request by jfilipcz**
#### What is this PR About?

* Added Templates for InstallPlan Approver
* Added a small tweak to OperatorHub templates to allow picking specific version of operator

#### How do we test this?
N/A

cc: @redhat-cop/day-in-the-life

### CODE REVIEW

**Review by tylerauerbeck — DISMISSED** [review]
LGTM

**Comment by tylerauerbeck** [comment]
@jfilipcz Looks like one of the tests checks to make sure that everything is a .yml file instead of .yaml . Mind making that change?

**Review by tylerauerbeck — APPROVED** [review]
LGTM

**Comment by oybed** [comment]
@jfilipcz can you please submit a follow-up PR for this with a README describing the content of the newly created `installplan-approver` section?

**Pull request merged**
