### PR TITLE
add docker-build-template-binary-to-dockerimage-with-push-secret.yml

### PR DESCRIPTION
**Pull request by itewk**

### CODE REVIEW

**Review by pabrahamsson — APPROVED** [review]
LGTM

**Comment by itewk** [comment]
@pabrahamsson thank you

**Comment by itewk** [comment]
@pabrahamsson can i request a new tag on this repo so we can point at the tag rather then master?

**Comment by pabrahamsson** [comment]
Sure thing @itewk 
https://github.com/redhat-cop/openshift-templates/releases/tag/v.1.4.3

**Comment by pabrahamsson** [comment]
Sorry, make that https://github.com/redhat-cop/openshift-templates/releases/tag/v1.4.3

**Pull request merged**
