### PR TITLE
init add - secrets/secret-docker-config-json.yml

### PR DESCRIPTION
**Pull request by itewk**

### CODE REVIEW

**Comment by oybed** [comment]
Looks related/similar to #24 - maybe we can just get the former finalized and close this one?

**Comment by itewk** [comment]
@oybed they do look similar indeed. mine assumes pre base64 encoded REPO_AUTH rather then separate username / pass strings, but that was only because I didn't know you could do it by passing the separate username/pass strings. maybe to resolve the issues people had with #24 merge the two to provide both options, either passs the base64 encoed `username:pass` or pass the seperate plane text username and pass?

**Comment by itewk** [comment]
@oybed @tylerauerbeck what do you all want to do here? if @tylerauerbeck PR is gonna get merged happy to retract this one or help contribute to @tylerauerbeck's, just want to see one of the two get merged in.

**Comment by tylerauerbeck** [comment]
@itewk I'm going to try to get my PR cleaned up today and see if there's anything we can merge from yours into mine. I'll tag you on my PR once it's updated so you can have a look as well.

**Comment by itewk** [comment]
@tylerauerbeck sounds good

**Comment by itewk** [comment]
@oybed and @tylerauerbeck i updated this PR to be in line with https://github.com/redhat-cop/openshift-templates/pull/24 and to update the nice shinny new README

**Review by tylerauerbeck — APPROVED** [review]
LGTM

**Pull request merged**
